#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# EC2 User-Data Bootstrap — Smart Attendance AIoT
# ─────────────────────────────────────────────────────────────────────────────
# Variables DB_HOST, DB_SECRET_ARN, REDIS_HOST, APP_REPO_URL, APP_BRANCH are
# injected by CDK at synthesis time (prepended to this script).
# ─────────────────────────────────────────────────────────────────────────────
#
# Log: sudo cat /var/log/cloud-init-output.log
# ─────────────────────────────────────────────────────────────────────────────

export DEBIAN_FRONTEND=noninteractive
APP_DIR="/opt/smart-attendance"
LOG_FILE="/var/log/smart-attendance-setup.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "═══════════════════════════════════════════"
echo " Smart Attendance — EC2 Bootstrap"
echo " $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
echo "═══════════════════════════════════════════"

# ─────────────────────────────────────────────────────────────────────────────
# 1. System updates & dependencies
# ─────────────────────────────────────────────────────────────────────────────
echo "▶ [1/7] System updates..."
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq \
    ca-certificates curl gnupg lsb-release unzip awscli git \
    libgl1-mesa-glx libglib2.0-0

# ─────────────────────────────────────────────────────────────────────────────
# 2. Docker Engine + Compose Plugin
# ─────────────────────────────────────────────────────────────────────────────
echo "▶ [2/7] Installing Docker..."
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) \
  signed-by=/etc/apt/keyrings/docker.gpg] \
  https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" \
  > /etc/apt/sources.list.d/docker.list

apt-get update -qq
apt-get install -y -qq \
    docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

systemctl enable docker
systemctl start docker
usermod -aG docker ubuntu

echo "  Docker: $(docker --version)"
echo "  Compose: $(docker compose version)"

# ─────────────────────────────────────────────────────────────────────────────
# 3. Clone application repository (if repo URL provided)
# ─────────────────────────────────────────────────────────────────────────────
echo "▶ [3/7] Cloning repository..."
mkdir -p "$APP_DIR"
if [ -n "$APP_REPO_URL" ]; then
    git clone --branch "$APP_BRANCH" --depth 1 "$APP_REPO_URL" "$APP_DIR"
    echo "  Cloned $APP_REPO_URL@$APP_BRANCH → $APP_DIR"
else
    echo "  ⚠️  APP_REPO_URL not set. Place your code in $APP_DIR manually."
fi
chown -R ubuntu:ubuntu "$APP_DIR"

# ─────────────────────────────────────────────────────────────────────────────
# 4. Fetch DB credentials from Secrets Manager
# ─────────────────────────────────────────────────────────────────────────────
echo "▶ [4/7] Fetching DB credentials from Secrets Manager..."
# Determine current AWS region from instance metadata
AWS_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region || echo "ap-southeast-1")

SECRET_JSON=$(aws secretsmanager get-secret-value \
    --secret-id "$DB_SECRET_ARN" \
    --region "$AWS_REGION" \
    --query SecretString \
    --output text)

DB_USER=$(echo "$SECRET_JSON" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['username'])")
DB_PASS=$(echo "$SECRET_JSON" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['password'])")
DB_NAME="attendance_db"

echo "  DB username: $DB_USER"
echo "  DB host:     $DB_HOST"

# ─────────────────────────────────────────────────────────────────────────────
# 5. Write production .env files
# ─────────────────────────────────────────────────────────────────────────────
echo "▶ [5/7] Writing environment files..."

# Generate random secrets
SECRET_KEY=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)

# ── backend/.env ────────────────────────────────────────────────────────────
cat > "$APP_DIR/backend/.env" <<EOF
# Auto-generated by EC2 bootstrap — DO NOT COMMIT
APP_NAME=Smart Attendance AIoT
APP_VERSION=1.0.0
DEBUG=false

DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}
REDIS_URL=redis://${REDIS_HOST}:6379/0

SECRET_KEY=${SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
JWT_SECRET_KEY=${JWT_SECRET}
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
ALGORITHM=HS256

ALLOWED_ORIGINS=["http://localhost:3000","https://REPLACE_WITH_YOUR_DOMAIN"]
RATE_LIMIT_PER_MINUTE=100

AI_SERVICE_URL=http://ai-service:8001
EOF

# ── ai-service/.env ────────────────────────────────────────────────────────
cat > "$APP_DIR/ai-service/.env" <<EOF
# Auto-generated by EC2 bootstrap — DO NOT COMMIT
REDIS_URL=redis://${REDIS_HOST}:6379/0
MIN_FACE_CONFIDENCE=0.6
MIN_BLUR_ENROLLMENT=20.0
MAX_FACES_PER_FRAME=10
EOF

# ── frontend/.env.local ────────────────────────────────────────────────────
# In EC2 docker-compose, frontend talks to backend via nginx proxy
cat > "$APP_DIR/frontend/.env.local" <<EOF
# Auto-generated by EC2 bootstrap — DO NOT COMMIT
NEXT_PUBLIC_API_URL=http://REPLACE_WITH_YOUR_DOMAIN/api
NEXT_PUBLIC_WS_URL=ws://REPLACE_WITH_YOUR_DOMAIN/ws
EOF

chmod 600 "$APP_DIR/backend/.env" "$APP_DIR/ai-service/.env" "$APP_DIR/frontend/.env.local"
echo "  .env files written."

# ─────────────────────────────────────────────────────────────────────────────
# 6. Write production docker-compose override + nginx config
# ─────────────────────────────────────────────────────────────────────────────
echo "▶ [6/7] Writing nginx config + compose override..."

# Nginx reverse proxy config
mkdir -p "$APP_DIR/nginx"
cat > "$APP_DIR/nginx/default.conf" <<'NGINX_EOF'
upstream backend  { server backend:8000; }
upstream frontend { server frontend:3000; }

server {
    listen 80;
    server_name _;

    client_max_body_size 50M;

    # WebSocket support
    location /ws/ {
        proxy_pass         http://backend;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
        proxy_read_timeout 3600;
    }

    # Backend API
    location /api/ {
        proxy_pass         http://backend;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # Frontend
    location / {
        proxy_pass         http://frontend;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
NGINX_EOF

# Production docker-compose override (uses RDS + ElastiCache, removes local db/redis)
cat > "$APP_DIR/docker-compose.prod.yml" <<COMPOSE_EOF
# Production override — used with: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# External managed services replace the local postgres/redis containers.

services:
  # Remove local DB and Redis (use RDS and ElastiCache instead)
  postgres:
    profiles: ["disabled"]

  redis:
    profiles: ["disabled"]

  backend:
    restart: unless-stopped
    env_file:
      - backend/.env
    # Override DATABASE_URL and REDIS_URL to point to managed services
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}"
      REDIS_URL: "redis://${REDIS_HOST}:6379/0"

  ai-service:
    restart: unless-stopped
    env_file:
      - ai-service/.env
    environment:
      REDIS_URL: "redis://${REDIS_HOST}:6379/0"

  frontend:
    restart: unless-stopped
    env_file:
      - frontend/.env.local

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
COMPOSE_EOF

echo "  nginx/default.conf and docker-compose.prod.yml written."

# ─────────────────────────────────────────────────────────────────────────────
# 7. Start application
# ─────────────────────────────────────────────────────────────────────────────
echo "▶ [7/7] Starting application with Docker Compose..."
cd "$APP_DIR"

if [ -f docker-compose.yml ]; then
    docker compose \
        -f docker-compose.yml \
        -f docker-compose.prod.yml \
        up -d --build 2>&1
    echo "  ✅ Application started."
else
    echo "  ⚠️  docker-compose.yml not found in $APP_DIR."
    echo "  Copy your project to $APP_DIR and run:"
    echo "    cd $APP_DIR && docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"
fi

# ── Systemd service for auto-restart on reboot ────────────────────────────
cat > /etc/systemd/system/smart-attendance.service <<UNIT_EOF
[Unit]
Description=Smart Attendance Docker Compose
After=docker.service network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${APP_DIR}
ExecStart=/usr/bin/docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
ExecStop=/usr/bin/docker compose -f docker-compose.yml -f docker-compose.prod.yml down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
UNIT_EOF

systemctl daemon-reload
systemctl enable smart-attendance

echo ""
echo "═══════════════════════════════════════════"
echo " Bootstrap complete — $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
echo "═══════════════════════════════════════════"
echo ""
echo " Next steps:"
echo "  1. Update ALLOWED_ORIGINS in backend/.env with your domain"
echo "  2. Update NEXT_PUBLIC_API_URL in frontend/.env.local"
echo "  3. Set up HTTPS with Let's Encrypt (certbot)"
echo "     sudo certbot --nginx -d your-domain.com"
echo ""
